sudo: required

services:
  - docker

notifications:
  email:
    on_success: never
    on_failure: always
    
addons:
  chrome: stable  
  
cache:
  directories:
    - "node_modules"

language: node_js
node_js:
  - "7"
 
before_script:
  - docker run -d --net=host selenium/standalone-chrome

script:
  - ./node_modules/.bin/codeceptjs run --steps
  
