sudo: required

services:
  - docker

addons:
  chrome: stable  
  artifacts:
    working_dir: output
  
cache:
  directories:
    - "node_modules"

language: node_js
node_js:
  - "7"
 
before_script:
  - npm install
  - docker run -d --net=host selenium/standalone-chrome

script:
  - docker ps
  - ./node_modules/.bin/codeceptjs run --steps
  
